# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01ee08ef33bb9b20eb7075e0f31ca92eee17552ab30ff290b7821e83dd7a04bf7e1d9cc751b0d1af215315272eeaa3bd7acefb39b6bdafe243ac90c0a8d0b90

test:
  secret_key_base: b98780e39d80ade26f2a513af6f6fe206e815cdeb254e3cbe87f342db0cb5c220508eda3caa61cc2075fb7331077115e7c6287c28c785c705a22d7883b08e289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
